### ISSUE TITLE
CDN Issues - Authorization

### ISSUE THREAD

**Issue by WebMDT-Marco** [szepeviktor/w3-total-cache-fixed#198]
Important Note: This issue occurs on W3TC Standard as well
WP Version: 4.6,4.6.1 & 4.7 the issue occurs (haven't tested lower)

Currently utilizing CLOUD FILES, after authorization (and a confirmed test) everything works great. However at some point one of the CRONS corrupts the authorization. I state that its corrupted, as the listed USERNAME/REGION/CONTAINER are correct ... however a TEST fails and any WP-MEDIA uploads fail. To rectify this, I do a "Reauthorize" with the same information and then everything is fine.

I'm seeing the following in my logs, however I'm not sure they're related.

I currently have 19 WP Installs on the same DOMAIN, all of which are experiencing this issue. 

`Fatal Error: Error: Cannot use object of type WP_Error as array
/var/www/vhosts/fairfieldschools.org/schools/fwhs/content/plugins/w3-total-cache/Cdn_RackSpace_Api_CloudFiles.php 100`

**Comment by amiga-500** [comment]
So, you are losing your Rackspace Cloudfiles authorization after a period of time and so it forces you to manually go to reauthorize it.  Correct? 

This sounds like a bug [i fixed](https://github.com/szepeviktor/w3-total-cache-fixed/issues/164#issuecomment-259175191) way, way back.

 If so, I pushed this fix into our [w3tc-0.-9-5 branch](https://github.com/szepeviktor/w3-total-cache-fixed/tree/w3tc-0-9-5) a while ago and involves simply replacing your existing `Cdn_Core.php` file (found within the _w3-total-cache_ directory) with this [updated version](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/w3tc-0-9-5/Cdn_Core.php).

Cheers
Kimberly :octocat:

**Comment by amiga-500** [comment]
Hi @WebMDT-Marco 

So, you are losing your Rackspace Cloudfiles authorization after a period of time and so it forces you to manually go to reauthorize it.  Correct? 

This sounds like a bug [i fixed](https://github.com/szepeviktor/w3-total-cache-fixed/issues/164#issuecomment-259175191) way, way back.

 If so, I pushed this fix into our [w3tc-0.-9-5 branch](https://github.com/szepeviktor/w3-total-cache-fixed/tree/w3tc-0-9-5) a while ago and involves simply replacing your existing `Cdn_Core.php` file (found within the _w3-total-cache_ directory) with this [updated version](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/w3tc-0-9-5/Cdn_Core.php).

Cheers
Kimberly :octocat:

**Comment by WebMDT-Marco** [comment]
Great! Yes I'm using the W3TC-FIX from the end of October (this fix was Nov 8th).

Much appreciated! Feel free to direct PM me if you ever need a hand with something so I can repay the HOURS of work you just saved me.

**Comment by amiga-500** [comment]
You're very welcome! :bowtie:
