### ISSUE TITLE
Question about existing Branches

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/w3-total-cache-fixed#203]
Hi @szepeviktor

Right now we have two branches:

* _master_
* _w3tc-0-9-5_

### _**master**_
As we are all aware, this branch is the default for this repository.  What isn't made clear to visitors (without reading the _ReadMe_ -- which i am updating) is that _master_ is specific to the **0.9.4.x** generation of W3TC fix updates.
### _**w3tc-0-9-5**_
This branch, as the name suggests, is home to the **0.9.5.x** generation of W3TC fix updates.

----

Both branches fill different voids for two sets of users.  The first branch, _master_, is for those who, for one reason or another, are unable to upgrade to 0.9.5.x and so, prefer to stick with this legacy version but still yearn for updates, security patches, and new features.

The other group, the ones using _w3tc-0-9-5_, want the latest build but still wish for updates, patches, and new features.

### Question 1
Because most visitors will not be aware of this, would it be better to create a new branch (from _master_) called _**version-0.9.4.x**_ and then delete _master_?  And also rename _w3tc-0-9-5_ to _**version-0.9.5.x**_?  This way we have two distinctly different but similarly named branches: _version-0.9.4.x_ and _version-0.9.5.x_ making it clearer what they both are about. 

I will be revising the _README.md_ file to make mention of the two generations and include links to their respective latest zip releases but just wanted to ask about this.

### Question 2

I was thinking the zips would have this naming convention:

_w3-total-cache-fixed-(for-0.9.4.x-users).zip_
_w3-total-cache-fixed-(for-0.9.5.x-users).zip_

Inside this zip (and therefore, extracted) it would conform to WP style and have a folder named after the exact directory name the plugin needs to be, which is: _**w3-total-cache-fixed**_ (so no renaming is required).  Is that okay or is it still best that the zip be simply called _w3-total-cache-fixed.zip_ for both branches?  I figured postfixing the extra part at the end of the zip would make it clearer which zip was for which audience.

Thanks for your input
Kimberly :octocat:

**Comment by rabin-io** [comment]
+1 for moving master to a more distinct branch of its own, and merging 0.9.5 into master, as the default RELEASE code.

Also i think this project should be renamed&called w3-total-cache-ce  (as community edition) because this branch is much more then just applying small fix/changes to the original code base.

**Comment by szepeviktor** [comment]
Please rename them yourselves

https://gist.github.com/lttlrck/9628955

then I delete the leftover.

Please consider chosing `v0.9.5.x` and `v0.9.4.x`

There have to be a default branch. Is it Ok to set the `v0.9.5.x` branch as default?

**Comment by nigrosimone** [comment]
v0.9.4.x is stable. v0.9.5.x have tons of bugs. For me the default branch is the stable and ready for producton v0.9.4.x

**Comment by amiga-500** [comment]
Thanks guys... will do

**Comment by amiga-500** [comment]
@szepeviktor  ok there are now two branches `v0.9.4.x` and `v0.9.5.x` ... the only thing left to do is for you to select the default branch.  As the others mentioned, because of stability, it's probably better to set the default branch as v0.9.4.x for now.  But i can see v0.9.5.x being the default in due time.  Btw, don't forget to delete the master branch after the switch.

**Comment by szepeviktor** [comment]
Done.
https://github.com/szepeviktor/w3-total-cache-fixed/branches
