### ISSUE TITLE
Error after install another plugin

### ISSUE THREAD

**Issue by fredroo** [szepeviktor/w3-total-cache-fixed#540]
after install and active plugin  **above the fold optimization** show this error:

`Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0`

look this
https://github.com/optimalisatie/above-the-fold-optimization/issues/14

please update this plugin to work better

**Comment by fredroo** [comment]
@szepeviktor please help me

**Comment by fredroo** [comment]
@andyexeter please help me

**Comment by fredroo** [comment]
@nigrosimone please help me

**Comment by szepeviktor** [comment]
Hello @fredroo !

Thank you for opening this issue.

This is a community fork of W3TC.
Maybe it is not the best way to alert contributors.

Although I am not a using this plugin you may contact me it you need immediate help - see my profile page.
