### ISSUE TITLE
Enable function

### ISSUE THREAD

**Issue by fredroo** [szepeviktor/w3-total-cache-fixed#541]
Please enable minify function 

 **Eliminate render-blocking CSS by moving it to HTTP body (Available after upgrade)**

follow this url:

wp-admin/admin.php?page=w3tc_minify

in minify css

loook this image
![minify w3 total cache cartao de credito sem anuidade wordpress](https://user-images.githubusercontent.com/6863089/32897092-77267bba-cac3-11e7-85f0-bc7e9f629cd0.png)

**Comment by fredroo** [comment]
@szepeviktor please help me

**Comment by fredroo** [comment]
@andyexeter please help me

**Comment by fredroo** [comment]
@nigrosimone please help me

**Comment by szepeviktor** [comment]
See https://github.com/szepeviktor/w3-total-cache-fixed/issues/540#issuecomment-344948058
